[package]
name = "micropub-rs"
version = "0.1.0"
authors = ["David Wilemski <david@wilemski.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bytes = "0.5"
chrono = "0.4"
diesel = { version = "1.4", features = ["sqlite", "r2d2"] }
itertools = "0.9"
indoc = "1.0"
markdown = "0.3"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1.2"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros"] }
url = "2.1"
warp = "0.2"

