[package]
name = "micropub_rs"
version = "0.3.2"
authors = ["David Wilemski <david@wilemski.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# name = "micropub_rs"

[dependencies]
anyhow = "1.0"
bytes = "0.5"
chrono = "0.4"
diesel = { version = "1.4", features = ["sqlite", "r2d2"] }
indoc = "1.0"
log = "0.4"
env_logger = "0.8"
markdown = "0.3"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = "1.2"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
url = "2.1"
# FIXME update once something higher than warp 0.2.5 is released. It
# contains a impl<Rejection> From<Reject> that really aids in error
# ergonomics (and some dependency removals/compilation speedups).
warp = { default-features = false, git = "https://github.com/seanmonstar/warp/", ref = "5e164616" }
